spring:
  application:
    name: api-weather-ms

server:
  port: 8083
# Configuracion para eureka client
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true

info:
  app:
    name: weather-service
    version: 1.0.0
    description: Get fast and easy access to the world's most accurate weather, ocean, environment and climate data for every location on earth.
