server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jonathanvictorica/spring-cloud
          default-label: semana-2
          force-pull: true
          search-paths: config-data




